registry:
  self-name: capitalizone

log:
  log-proxy:
    host: ""
    port: 6379
    key: ca_log

redis:
  nodes: []

# 级联 CA 配置项
keymanager:
  upper-ca:
    - "" # https://user:password@server.ca
  self-sign: false # 开启表示 ROOT CA
  csr-templates:
    root-ca:
      o: CI123 ROOT AUTHORITY
      expiry: 175200h
    intermediate-ca:
      o: SITE CA IDENTIFY
      ou: "spiffe://site/cluster"
      expiry: 175200h

singleca:
  config-path: ""

election:
  enabled: false
  id: capitalizone-leader
  baseon: configmap
  always-leader: false

gateway-nervs:
  enabled: false
  endpoint: ""

http:
  ca-listen: 0.0.0.0:8081
  listen: 0.0.0.0:8080

mysql:
  dsn: ""

influxdb:
  enabled: true
  address: "MSP_CUSTOM_INFLUXDB_ADDRESS" #192.168.2.80:8086
  port: 8086
  udp_address: "MSP_CUSTOM_INFLUXDB_UDP_ADDRESS" #influxdb msp数据库的udp地址，ip:port
  database: "MSP_CUSTOM_INFLUXDB_DATABASES" # 数据库名称
  precision: "ms" #精度 n, u, ms, s, m or h
  username: "MSP_CUSTOM_INFLUXDB_USERNAME"
  password: "MSP_CUSTOM_INFLUXDB_PASSWORD"
  read-username: "MSP_CUSTOM_INFLUXDB_USERNAME"
  read-password: "MSP_CUSTOM_INFLUXDB_PASSWORD"
  max-idle-conns: 30
  max-idle-conns-per-host: 30
  flush-size: 20 #批量发送的点的个数
  flush-time: 10 #定时批量发送点的时间，单位：s

mesh:
  msp-portal-api: "http://msp-portal:9080"

swagger-enabled: false

debug: false

version: "0.1"